spring:
  profiles.active: local
  application.name: liquibase-example
liquibase:
  change-log: classpath:db/db.master.xml
---
spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/liquibase
    username: postgres
    password: hendi34
  jpa:
    database: postgresql
    show-sql: true
liquibase:
  enabled: true
  drop-first: false
  contexts: local
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/liquibase
    username: postgres
    password: hendi34
  jpa:
    database: postgresql
    show-sql: true
liquibase:
  enabled: true
  drop-first: false
  contexts: dev
---
spring:
  profiles: integration-test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/liquibase
    username: postgres
    password: hendi34
  jpa:
    database: postgresql
    show-sql: false
liquibase:
  enabled: true
  drop-first: true
  contexts: test
---
spring:
  profiles: prod
  datasource:
    jndi-name: java:jboss/datasources/pocDS
  jpa:
    database: postgresql
    show-sql: false
liquibase:
  enabled: false
  context: prod
