-- liquibase formatted sql
-- changeset yuji:1677359372272-1
CREATE TABLE groups
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_time  TIMESTAMP(6) WITHOUT TIME ZONE,
    description   VARCHAR(500),
    modified_time TIMESTAMP(6) WITHOUT TIME ZONE,
    name          VARCHAR(100),
    CONSTRAINT "groupsPK" PRIMARY KEY (id)
);

-- changeset zuhaimi:1677359372272-2
ALTER TABLE
    groups
    ADD
        CONSTRAINT uc_groupsdescription_col UNIQUE (description);

-- changeset zuhaimi:1677359372272-3
ALTER TABLE
    groups
    ADD
        CONSTRAINT uc_groupsname_col UNIQUE (name);
