-- liquibase formatted sql
-- changeset yuji:1677359720411-3
CREATE TABLE department
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT "departmentPK" PRIMARY KEY (id)
);
